### ISSUE TITLE
Datasheet location

### ISSUE THREAD

**Issue by jjrh** [RobTillaart/PT2314#7]
Where did you find the datasheet describing i2c? The datasheet I see on princeton.com.tw is 5 pages and only shows pin functions. Same deal with the other chips I looked at. 

Is the full datasheet only available on request or something?

**Comment by RobTillaart** [comment]
This one is 20 pages.

[PT2314_3.pdf](https://github.com/user-attachments/files/15566491/PT2314_3.pdf)

**Comment by RobTillaart** [comment]
I have 4 PDF's, will add them to the repo.

**Comment by RobTillaart** [comment]
Done

**Comment by RobTillaart** [comment]
Link might be - http://www.turuta.md/DSHEETS/PT2314_3.pdf

**Comment by RobTillaart** [comment]
As I assume this is solved I close the issue.
